### ISSUE TITLE
Unit test overridden values

### ISSUE THREAD

**Issue by yaroslavche** [spatie/enum#104]
Hello. Thanks for package, it's very useful until 8.1.
I've faced one issue with testing. I want to cover with unit tests overridden values.
I have an enum with few overridden values, since they can't be declared as method name because of dot in value:
```php
<?php

declare(strict_types=1);

namespace Namespace\Type;

use Spatie\Enum\Enum;

/**
 * Value taken at start of interruption.
 * @method static self InterruptionBegin()
 *
 * Value taken when resuming after interruption.
 * @method static self InterruptionEnd()
 *
 * Value for any other situations.
 * @method static self Other()
 */
final class ReadingContext extends Enum
{
    /** @return array<string, string> */
    protected static function values(): array
    {
        return [
            'InterruptionBegin' => 'Interruption.Begin',
            'InterruptionEnd' => 'Interruption.End',
        ];
    }
}
```
And my test:
```php
<?php

declare(strict_types=1);

namespace Namespace\Tests\Type;

use Namespace\Type\ReadingContext;
use Generator;
use PHPUnit\Framework\TestCase;
use Spatie\Enum\Phpunit\EnumAssertions;

use function PHPUnit\Framework\assertSame;

class ReadingContextTest extends TestCase
{
    /** @dataProvider dataProvider */
    public function testValues(ReadingContext $context, string $expected): void
    {
        EnumAssertions::assertIsEnum($context);
        EnumAssertions::assertSameEnumValue($context, $expected);
        assertSame($context->value, $expected);
    }

    /** @return Generator<int, array<int, mixed>> */
    public function dataProvider(): Generator
    {
        yield [ReadingContext::InterruptionBegin(), 'Interruption.Begin',];
        yield [ReadingContext::InterruptionEnd(), 'Interruption.End',];
    }
}
```
Tests passed fine, but I got in coverage result that `ReadingContext::values()` doesn't covered.
So my question is why not covered and maybe you could suggest how I can achieve that? PHP 8.0.8, PHPUnit 9.5.6
Thanks

**Comment by Gummibeer** [comment]
The reason is that you don't access the enum in your test method but the data provider. These are executed outside the normal context (possibly even a different process) why you can't use things like Laravel/Symfony Container or other more complex dependencies in them.
That's why xDebug doesn't see the call to the enum methods.
One way to solve it would be to pass the method name as string from the data provider and call `ReadingContext::from($name)` in your test method. That way you should get a proper coverage report.

Another thing: we will proceed the package even after PHP8.1 (see #96) - as the native enums are a massive improvement but we want to keep some of the current methods/features and also need them for the Laravel Wrapper.
So just to let you know - it's up to you how you want to switch. 😉

**Comment by yaroslavche** [comment]
yes, it works fine now. Thanks for explanation!
I'm writing framework agnostic package and in 8.1 planning to move to built-in enums because enums in my package never wouldn't change and right now `spatie/enum` is just single dependency and it would be better without any of dependencies. But maybe will leave this package, I will see later at autumn.
Many thanks for quick response and your work! Appreciated

**Comment by Gummibeer** [comment]
The new version will integrate with native enums. So you will use `enum ReadingContext` but have methods like the `values()`, `labels()` and `equals()` on it.
If you don't need these things or think that you don't need the package for it - totally fine! 👍 
Just wanted to let you know that we won't abandon that package but bring it to the next level.^^
