### ISSUE TITLE
Using an Enum as a Class Property or Method Parameter

### ISSUE THREAD

**Issue by frost-byte** [spatie/enum#35]
Is it possible to use an Enum as a class property and assign a default value?  It seems like I cannot initialize a member/field of my classes using the Enums I've created.

Should one of these two approaches work?
The first doesn't result in an error, but does not appear to function property;
The second gives the error _Constant expression contains invalid operations_

```php
   /**
    * @var MonthEnum $month
    */
   private $month = MonthEnum::january;
```
```php
   /**
    * @var MonthEnum $month
    */
   private $month = MonthEnum::january();
```

I also have this same issue if I try to set a default value for a method/function parameter.
Surely there's a way to do this without having to explicitly assign the default in a constructor or method body - when no parameter value is provided?

**Comment by Gummibeer** [comment]
The problem is how this works and that PHP doesn't allow method calls/class instances as default value for properties/arguments.

The best and shortest solution I see would be the null coalescing operator `??`.
So have `null` or nothing as default and do `$enum = $enum ?? MonthEnum::january()`.

I also see no way to add anything to the package to allow enums as default.

**Comment by frost-byte** [comment]
So something like this?

```php
   /**
    * @var MonthEnum $month
    */
   private $month = null;

public function __construct(?MonthEnum $month = NULL) {
    $this->month = $month ?? MonthEnum::january();
}
```

**Comment by Gummibeer** [comment]
Exactly.

**Comment by brendt** [comment]
Unfortunately these are indeed limitations of PHP, for now using null coalescing is the only way to do this.
