### ISSUE TITLE
GetNames doesn't return the custom names

### ISSUE THREAD

**Issue by DjustinK** [spatie/enum#49]
```php
<?php

namespace App\Enums;

use Spatie\Enum\Enum;

class RegionEnum extends Enum
{
    public static function ea(): RegionEnum
    {
        return new class() extends RegionEnum {
            public function getName(): string
            {
                return 'East-Africa';
            }

            public function getIndex(): int
            {
                return 0;
            }
        };
    }

    public static function wa(): RegionEnum
    {
        return new class() extends RegionEnum {
            public function getName(): string
            {
                return 'West-Africa';
            }

            public function getIndex(): int
            {
                return 1;
            }
        };
    }

    public static function sa(): RegionEnum
    {
        return new class() extends RegionEnum {
            public function getName(): string
            {
                return 'South-Africa';
            }

            public function getIndex(): int
            {
                return 2;
            }
        };
    }

    public static function global(): RegionEnum
    {
        return new class() extends RegionEnum {
            public function getName(): string
            {
                return 'Global';
            }

            public function getIndex(): int
            {
                return 3;
            }
        };
    }
}

```

Calling `RegionEnum::getNames();` returns the name of the functions instead of the name.

```php
array:4 [▼
  0 => "EA"
  1 => "WA"
  2 => "SA"
  3 => "GLOBAL"
]
```

**Comment by Gummibeer** [comment]
Hey,
this is intended. The names are only for internal use of the package.

> **Word definition**
> * Name is the uppercased method name - it is only used to make an enum.
> * Value is the string returned by getValue() - by default it’s the name but you can customize it.
> * Index is the integer returned by getIndex() - by default it’s the array key of the enum value it get’s during resolve but you can customize it.

https://docs.spatie.be/enum/v2/introduction/

The `name` is also only resolved once instead of `index` and `value` these are resolved from the `MAP_` constants and custom methods:
https://github.com/spatie/enum/blob/5fd41561bb7eecbd5d3e9cfbbbc6370c23c41b9b/src/Enum.php#L254-L267
So depending on your needs you can override the `getValue()` method or even only use the `MAP_` constants. Or add a new method like `getHumanName()` or however you want to name it.
