### ISSUE TITLE
Questions about specification

### ISSUE THREAD

**Issue by gitetsu** [spatie/enum#75]
Hi.

In v3,
 - make by label (which is [make by value](https://spatie.be/docs/enum/v2/usage/make-enum#make-by-value) of v2)
 - [Get all](https://spatie.be/docs/enum/v2/usage/make-enum#get-all)

are no longer supported?
Are these by design?

Last but not least, thank you for creating your great packages!

**Comment by Gummibeer** [comment]
Hey,

you are right - with both points.

Instantiating by *new* `label` isn't supported as we haven't found any real use case for this.
If you have one in which you have to instantiate by `label` I would be happy to hear why! 🙂

The `getAll()` method was the same - it would be easy to add. But for what do you need an array of all instances of the enum? 🤔

**Comment by gitetsu** [comment]
Thank you for quick response!

In my case, I used this package via `spatie/laravel-enum`, and created enum something like below:

```php

// v2 code
use Spatie\Enum\Enum

/**
  * @method static self ALL()
  * @method static self VIEW()
  * @method static self CREATE()
  */
final class RepositoryPermission extends Enum
{
	protected const MAP_VALUE = [
        'ALL' => 'repository.*',
		'VIEW' => 'repository.view',
		'CREATE' => 'repository.create',
	];
}
```

Method name and value(label) name are completely different, and these values(`repository.*`, etc) are stored in a database.
So it would be great if I could instantiate by label without overriding `Spatie\Enum\Laravel\Enum::castUsing()`.

The `getAll()` is used in my seeder, but it's not very important and `toArray()` seems to be a good substitute.
If anything, I was just curious. :wink:

Thanks!

**Comment by gitetsu** [comment]
On second thought, I used `getAll()` when passing an enum as an argument to some method in a loop.

For example,
```php
// PlatformEnum is iOS, Android, Windows, MacOS, Linux...
foreach (PlatformEnum::getAll() as $platform) {
    $this->doSomething($platform);
}
```

Although I don't use it often, but if I have a lot of values like this or don't know whole values, I think it's useful to have it.

**Comment by Gummibeer** [comment]
Your first issue: you could define `repository.*` as `value` and `all` as `label`.
This way you can use `RepositoryPermission::ALL()` and `RepositoryPermission::make('repository.*')`.

The second one, seeding, have you seen that we provide a Faker provider to generate random enum in factories which should be used in seeders? That should solve your requirement in the best way. 🎉

The third one: okay, that's something you can't do in a pretty way right now. 🤔
But naming wise I would use `all()` right now which would very likely conflict with several Installations. I will keep an eye on it - for the moment I recommend you to add your own base enum class with this method.

Because some haven't seen it - the Laravel wrapper has it's own base enum class. With v2 it's much more important as otherwise the casting like described doesn't work.

PS: we also have phpunit assertions you can use. 😉

**Comment by gitetsu** [comment]
> Your first issue: you could define repository.* as value and all as label.

Ah, I should’ve come up with this. 😓 
I'll try to take your advice on the other stuff as well.

I really appreciate your kindness!
Again, thank you for your great packages!
